name: 'Deploy to Azure Web App'
description: 'Deploy Docker image to Azure Web App'
inputs:
  CREDS:
    description: 'Azure credentials'
    required: true
  WEBAPP_NAME:
    description: 'Web App name'
    required: true
  REGISTRY_LOGIN_SERVER:
    description: 'Registry login server'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Lowercase the repo name
      shell: bash
      run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
      
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ inputs.CREDS }}

    - name: 'Deploy'
      uses: azure/webapps-deploy@v2
      id: deploy-to-webapp
      with:
        app-name: ${{ inputs.WEBAPP_NAME }}
        slot-name: 'staging'
        images: ${{ inputs.REGISTRY_LOGIN_SERVER }}/privacy-helper:${{ github.sha }}