# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and Deploy

on:
  workflow_call:
    inputs:
      target-env:
        required: true
        type: string
    secrets:
      REGISTRY_LOGIN_SERVER:
        required: true
      REGISTRY_USERNAME:
        required: true
      REGISTRY_PASSWORD:
        required: true
      CREDS:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
        name: ${{ inputs.target-env }}
    steps:
      - uses: actions/checkout@v4

      - name: Lowercase the repo name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - run: |
          docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/privacy-helper:${{ github.sha }}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/privacy-helper:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: ${{ inputs.target-env }}
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Lowercase the repo name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
            creds: ${{ secrets.CREDS }}

      - name: 'Deploy'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: ${{ secrets.WEBAPP_NAME }}
          slot-name: 'staging'
          images: ${{ secrets.REGISTRY_LOGIN_SERVER }}/privacy-helper:${{ github.sha }}