# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and Deploy MSFT Tenant

on:
  push:
    branches:
      - main
    paths:
        - 'src/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
jobs:
  build-and-deploy-to-msft-tenant:
    runs-on: ubuntu-latest
    environment:
      name: Microsoft
    steps:
      - uses: actions/checkout@v4
      - name: Build docker image
        uses: ./.github/actions/build
        with:
          REGISTRY_LOGIN_SERVER: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          REGISTRY_NAME: athenaprivacyreviewbeta
      - name: Deploy to prod
        uses: ./.github/actions/deploy
        with:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          WEBAPP_NAME: ${{ secrets.WEBAPP_NAME }}
          REGISTRY_LOGIN_SERVER: ${{ secrets.REGISTRY_LOGIN_SERVER }}