# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Release to Microsoft

on:
  workflow_dispatch:

jobs:     
  release-to-prod:
    name: Release to prod
    runs-on: ubuntu-latest
    environment:
      name: Microsoft

    steps:
      - name: Deploy to staging
      uses: ./.github/swap_slots/deploy
      with:
        CREDS: ${{ secrets.CREDS }}
        WEBAPP_NAME: ${{ secrets.WEBAPP_NAME }}
        RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}